<link href="<?php echo $this->getSkinUrl('gallery/css/gallery.css')?>" type="text/css" media="all" rel="stylesheet"/>
<link href="<?php echo $this->getSkinUrl('gallery/css/lightbox.css')?>" type="text/css" media="all" rel="stylesheet"/>
<script src="<?php echo $this->getSkinUrl('gallery/js/lightbox.js')?>" type="text/javascript"></script>
<script type="text/javascript">
	var fileLoadingImage = "<?php echo $this->getSkinUrl('gallery/images/loading.gif') ?>";		
	var fileBottomNavCloseImage = "<?php echo $this->getSkinUrl('gallery/images/closelabel.gif') ?>";
</script>
<?php if(Mage::helper('gallery')->getDescription()): ?>
	<div><?php echo $this->getAlbum()->getContent() ?></div>
<?php endif;?>
<div class="gallery-container album">		
	<ul>
		<?php $collection = $this->getPhotos();
			foreach ($collection as $item) { 
			?>
			<li>
				<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $item->getFilename() ?>" rel="lightbox[projects]" title="<?php echo $item->getTitle() ?>" ><img src="<?php echo $this->helper('gallery/image')->init($item->getFilename())->resize(175, 131) ?>" /></a>
			</li>
		<?php } ?>			
	</ul>
	<div style="clear:both; float:right"><a href="<?php echo $this->getUrl('gallery') ?>"><?php echo Mage::Helper('gallery')->__('View Album') ?></a></div>
</div>